name: Go Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.0

    - name: Run go mod tidy
      run: go mod tidy

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.58

    - name: Run golangci-lint
      run: |
        golangci-lint run
